project:
  type: website
  output-dir: "docs"

website:
  title: "JP's Projects"
  navbar:
    left:
      - icon: github
        href: https://github.com/jpquast
      - icon: twitter
        href: https://twitter.com/QuastJP
    right:
      - about.qmd
      - text: "Blog"
        href: index.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    code-overflow: wrap
    link-external-newwindow: true

